export const ADMIN_GET_LIST_USER_SUCCESS = 'ADMIN_GET_LIST_USER_SUCCESS'
export const ADMIN_GET_LIST_USER_FAIL = 'ADMIN_GET_LIST_USER_FAIL'


export const USER_GET_QUESTION_SUCCESS = 'USER_GET_QUESTION_SUCCESS'
export const ADMIN_GET_QUESTION_SUCCESS = 'ADMIN_GET_QUESTION_SUCCESS'

export const USER_GET_QUESTION_FAIL = 'USER_GET_QUESTION_FAIL'
export const ADMIN_GET_QUESTION_FAIL = 'ADMIN_GET_QUESTION_FAIL'

export const USER_SUBMIT_ANSWER_SUCCESS = 'USER_SUBMIT_ANSWER_SUCCESS'
export const USER_SUBMIT_ANSWER_FAIL = 'USER_SUBMIT_ANSWER_FAIL'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'
export const CLEAR_USER = 'CLEAR_USER'

export const USER_UPDATE_NEW_TOKEN_SUCCESS = 'USER_UPDATE_NEW_TOKEN_SUCCESS'
export const USER_UPDATE_NEW_TOKEN_FAIL = 'USER_UPDATE_NEW_TOKEN_FAIL'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const CLEAR_PRODUCT = 'CLEAR_PRODUCT'

export const REFRESH_TOKEN = 'REFRESH_TOKEN'